# PostgreSQL Database Configuration
#spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres
#spring.datasource.username=postgres.chcfvlpumiszoleaceab
#spring.datasource.password=basededatos123
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.url=jdbc:postgresql://localhost:5432/stockmaster
#spring.datasource.username=postgres
#spring.datasource.password=05c4r4lb31r0
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://dpg-d7omtcfavr4c73cb9av0-a.oregon-postgres.render.com:5432/stockmaster_bkg9
spring.datasource.username=stockmaster_bkg9_user
spring.datasource.password=Q20LdeakKeOCd6WIwKNxJVcHbMW9DfDj
# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

session.inactivity.minutes=30

logging.level.org.springframework.security=DEBUG